prep-css-box-model -Tim Chiang
tychiang922/prep-0422-code-solutions pull request #7
Opened 2022-04-20 23:37 UTC by tychiang922

![box model screenshot](https://user-images.githubusercontent.com/103610490/164341655-245cd764-3a0f-4436-91a9-4db8a97d2171.png)

2022-04-21 17:08 UTC, thebearingedge requested changes

2022-04-21 17:08 UTC, thebearingedge commented on prep-css-box-model/style.css
> +  border: 3px, double, darkgray;
Hi Tim, you border styling isn't being applied due to the commas here, try removing them.

2022-04-21 21:27 UTC, tychiang922 commented
![box model revised](https://user-images.githubusercontent.com/103610490/164555141-bdd70b92-808f-44f3-bcf0-e364b1001a22.png)

2022-04-22 00:25 UTC, thebearingedge approved these changes

2022-04-22 02:20 UTC, merged